# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Prof. Rodolfo Marinho, MSc.
email: rodolfo@rodolfomarinho.com
host: 0.0.0.0
port: 443
description:
  pt: Rodolfo Marinho é mestre em Ciência da Computação pela Universidade Federal de Campina Grande, com ênfase na área de Segurança e Privacidade de Dados. Atualmente, está docente do curso de Sistemas de Informação na Unifacisa, onde leciona as disciplinas de Programação I e Fundamentos Lógicos da Computação.
  en: Rodolfo Marinho is an MSc. in Computer Science from the Federal University of Campina Grande, with emphasis in Data Security and Privacy. Currently, he is a professor of the Information Systems course at Unifacisa, lecturing Programming I and Fundamentals of Logic in Computer Science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rodolfomarinho.com" # the base hostname & protocol for your site, e.g. http://example.com
author: rodolfoams
linkedin_username: rodolfoams
github_username:  rodolfoams

# Build settings
markdown: kramdown
theme: minima
encoding: utf-8
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
